FROM tomcat:jre8
MAINTAINER BSI-Business-Systems-Integration-AG

ADD org.eclipse.scout.hellojava.ui.html.app.dev-7.0.300-SNAPSHOT.war /usr/local/tomcat/webapps/hellojava.war

CMD ["catalina.sh", "run"]